var signatureMap = {
  'login': {
    'username': String,
    'password': String,
    'machine': String,
    'version': num,
  },
  'list_disk_usage': {},
  'create_mailbox': {
    'mailbox': String,
    'enable_spam_protection': bool,
    'discard_spam': bool,
    'spam_redirect_folder': String,
    'use_manual_procmailrc': bool,
    'manual_procmailrc': String,
  },
  'delete_mailbox': {
    'mailbox': String,
  },
  'list_mailboxes': {},
  'update_mailbox': {
    'mailbox': String,
    'enable_spam_protection': bool,
    'discard_spam': bool,
    'spam_redirect_folder': String,
    'use_manual_procmailrc': bool,
    'manual_procmailrc': String,
  },
  'create_email': {
    'email_address': String,
    'targets': String,
    'autoresponder_on': bool,
    'autoresponder_subject': String,
    'autoresponder_message': String,
    'autoresponder_from': String,
    'script_machine': String,
    'script_path': String,
  },
  'delete_email': {
    'email_address': String,
  },
  'list_emails': {},
  'update_email': {
    'email_address': String,
    'targets': [''].runtimeType,
    'autoresponder_on': bool,
    'autoresponder_subject': String,
    'autoresponder_message': String,
    'autoresponder_from': String,
    'script_machine': String,
    'script_path': String,
  },
  'create_certificate': {
    'name': String,
    'certificate': String,
    'private_key': String,
    'intermediates': String,
  },
  'delete_certificate': {
    'name': String,
  },
  'list_certificates': {},
  'update_certificate': {
    'name': String,
    'certificate': String,
    'private_key': String,
    'intermediates': String,
  },
  'create_domain': {
    'domain': String,
    'subdomain': String,
  },
  'delete_domain': {
    'domain': String,
    'subdomains': String,
  },
  'list_domains': {},
  'create_website': {
    'website_name': String,
    'ip': String,
    'https': bool,
    'subdomains': List,
    'site_apps': List,
  },
  'delete_website': {
    'website_name': String,
    'ip': String,
    'https': bool,
  },
  'list_bandwidth_usage': {},
  'list_websites': {},
  'update_website': {
    'website_name': String,
    'ip': String,
    'https': bool,
    'subdomains': List,
    'site_apps': List,
  },
  'create_app': {
    'name': String,
    'type': String,
    'autostart': bool,
    'extra_info': String,
    'open_port': bool,
  },
  'delete_app': {
    'name': String,
  },
  'list_apps': {},
  'list_app_types': {},
  'create_cronjob': {
    'line': String,
  },
  'delete_cronjob': {
    'line': String,
  },
  'create_dns_override': {
    'domain': String,
    'a_ip': String,
    'cname': String,
    'mx_name': String,
    'mx_priority': String,
    'spf_record': String,
    'aaaa_ip': String,
    'srv_record': String,
  },
  'delete_dns_override': {
    'domain': String,
    'a_ip': String,
    'cname': String,
    'mx_name': String,
    'mx_priority': String,
    'spf_record': String,
    'aaaa_ip': String,
    'srv_record': String,
  },
  'list_dns_overrides': {},
  'change_db_user_password': {
    'username': String,
    'password': String,
    'db_type': String,
  },
  'create_db': {
    'name': String,
    'db_type': String,
    'password': String,
    'db_user': String,
  },
  'create_db_user': {
    'username': String,
    'password': String,
    'db_type': String,
  },
  'delete_db': {
    'name': String,
    'db_type': String,
  },
  'delete_db_user': {
    'username': String,
    'db_type': String,
  },
  'enable_addon': {
    'database': String,
    'db_type': String,
    'addon': String,
  },
  'grant_db_permissions': {
    'username': String,
    'database': String,
    'db_type': String,
  },
  'list_dbs': {},
  'list_db_users': {},
  'revoke_db_permissions': {
    'username': String,
    'database': String,
    'db_type': String,
  },
  'replace_in_file': {
    'filename': String,
    'changes': List,
  },
  'write_file': {
    'filename': String,
    'str': String,
    'mode': String,
  },
  'change_user_password': {
    'username': String,
    'password': String,
  },
  'create_user': {
    'username': String,
    'shell': String,
    'groups': [''].runtimeType,
  },
  'delete_user': {
    'username': String,
  },
  'list_users': {},
  'list_ips': {},
  'list_machines': {},
  'run_php_script': {
    'script': String,
    'code_before': String,
  },
  'set_apache_acl': {
    'paths': ['a'].runtimeType,
    'permission': String,
    'recursive': bool,
  },
  'system': {
    'cmd': String,
  },
};
