name: webfaction_api
description: A client for the Webfaction API
version: 0.8.0
author: Brian McClure
documentation:
environment:
  sdk: '>=1.24.0 < 2.0.0'

dependencies:
  xml_rpc: '>=0.1.4'
dev_dependencies:
  test: ^0.12.0
