name: webfaction_api
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '< 2.0.0'

dependencies:
  xml_rpc: '>=0.1.4'
dev_dependencies:
  test: ^0.12.0
