name: webfaction_api
description: A client for the Webfaction API
version: 0.9.0
author: Brian McClure <brian@mcclure.pw>
homepage: https://github.com/brmc/dart-webfaction-api
documentation:
environment:
  sdk: '>=1.24.0 < 3.0.0'
dependencies:
  xml_rpc: '^0.2.1'
dev_dependencies:
  test: '>=0.12.0'
